// Shim bridging to the brlapi.h generated by the BRLTTY build.
// Run Scripts/build-brltty-macos.sh before building this package.
//
// BRLAPI_NO_SINGLE_SESSION removes the global-state (single-session) API so
// only the handle-based brlapi__ functions are visible, preventing accidental
// use of shared mutable state from actor code.
#define BRLAPI_NO_SINGLE_SESSION
#include "../../.build/brltty/Programs/brlapi.h"
